### ISSUE TITLE
Database communication

### ISSUE THREAD

**Issue by 153957** [HiSPARC/hisparcdaq#4] opened 2012-02-20 09:41 UTC
The DAQ (III v1) may loose its connection with the database and not attempt to reestablish it, but will attempt to use it.
This will cause a memory build up, resulting in a crash of the DAQ.

Has been tested (and confirmed) on Windows XP with both an HiSPARC II and III box and on Windows 7 with an HiSPARC II box.

**Comment by kleiram** [comment] 2012-02-28 13:20
A possible solution for this is to have a limit on the amount of retries that are allowed. At the moment there's no limit and the data that should be written to the database is saved in memory, like you said. When the retry limit is reached, the data is written to a local file (a CSV or JSON file or the likes) and have a periodic (with a smaller frequency) check to see if the database is reachable again.

**Comment by davidfokkema** [comment] 2012-02-29 15:08
Better yet: parse the error code. Generally, the MySQL database is fully operational (upon investigating such issues before the system runs out of memory, invariably this is the case). So I'd say that the connection to the database is closed for whatever reason, but can be re-established immediately. So retries don't make much sense, in this respect. Just open a new connection (which _never_ happens in the current code).

Yes, we can implement _another_ datastore; this time a local file to which LabVIEW writes data. But then we need to implement a client which can empty that file into the buffer, either automatically in LabVIEW, or manually (e.g. in Python). But I'd say that this is a bit of overkill. Just accept the fact that sometimes the system goes down. As of now, there is no clear indication that this happens to MySQL itself, _ever_. If you fix LabVIEW to re-establish connections, I think you have fixed the whole problem.

**Comment by kleiram** [comment] 2012-03-02 12:25
If I interpret the code correctly, there are attempts to reconnect to the database:

![LabVIEW reconnect to database](http://i.imgur.com/6lr9J.png)

As you can see, there's a retry after three seconds...

**Comment by davidfokkema** [comment] 2012-03-02 12:32
This depends on the definition of 'not connected'.  The error log seems to suggest that LabVIEW enters an infinite loop in which it tries to store data in the database many, many times a second. I don't think the DAQ software is aware of the fact that the connection is closed, since it doesn't check the return code. Mind, this is pure speculation on my part. But the observed behavior fits the hypothesis.

**Comment by kleiram** [comment] 2012-03-02 12:46
Agreed. What's the average number of events per second? But I don't see why it should go into an infinite loop, since there's clearly a timeout installed...but your point does make sense.

**Comment by davidfokkema** [comment] 2012-03-02 12:51
I'm not sure. But it really is a _lot_. The process becomes CPU bound as it is trying to store event data and write to the error log as fast as it can. You might be able to simulate it by just shutting down the MySQL server and restarting it after LabVIEW starts complaining.

**Comment by kleiram** [comment] 2012-04-24 07:59
I think I found the cause of the issue:

When the database connection is lost (i.e. by killing the MySQL daemon) the database handle is not invalidated so the LabVIEW application still believes it's connected to the database. You can check if the handle is valid or not, but if it is indeed still valid (but actually not connected) errors occure. So there are two possible solutions:
1. Open a connection with data store iteration and close it when it's done
2. Before each iteration, check if the handle is actually valid

The main issue with solution 1 is that I think that it's pretty heavy on the CPU (the data store loop is called a lot). The issue with solution 2 is that I'm not sure how to do that. There are of course nasty ways to do it, run a `SELECT` statement and see if an error occures, if so, check if it is a database connection error but that's not clean...

**Comment by davidfokkema** [comment] 2012-04-24 12:25
I think there is a third option, which I very much prefer: inspect the error code for all database transactions. When the error indicates that the connection is lost, or handle is not valid, or whatever, open a new connection and try again.

I'm against your option 1. Your option 2., if you replace `SELECT` statement with: just store the data, it is identical to the previously suggested option, but without the overhead.

**Comment by kleiram** [comment] 2012-05-02 09:56
Fixed in commit 8ff68e6060f067b856c328e83cc86f47fe54545c

> The VI where the data is written to the MySQL database
> now checks the result of the query. If this is an error
> corresponding to the error code of a ODBC connection
> error, the VI will set the MySQL connection status
> to disconnected. When the MySQL database is back up,
> the connection will be re-established and the data
> backed-up in the queues will be written to the database.

**Closed as completed** 2012-05-02 09:57 UTC
Labels: critical
